fortanix/rust-sgx

Cargo.lock
doc/FORTANIX-SGX-ABI.md

Missed changes to changelog and Cargo.lock in #45

Updates for fortanix-sgx-abi 0.3.2

---

Cargo.lock
fortanix-sgx-tools/src/bin/ftxsgx-runner.rs
sgxs-loaders/Cargo.toml
sgxs-loaders/src/generic.rs
sgxs-loaders/src/isgx/mod.rs
sgxs-loaders/src/lib.rs
sgxs-loaders/src/sgx_enclave_common/defs.rs
sgxs-loaders/src/sgx_enclave_common/mod.rs
sgxs-tools/src/bin/sgxs-load.rs
sgxs/src/einittoken.rs
sgxs/src/sgxs.rs

Add libsgx_enclave_common enclave loader

---

.travis.yml

Added Travis CI support. 
Currently this just checks if build succeeds. No tests are run.

Add .travis.yml to enable travis CI

---

fortanix-sgx-tools/src/bin/ftxsgx-runner.rs
sgxs-loaders/src/generic.rs
sgxs-loaders/src/isgx/ioctl.rs
sgxs-loaders/src/isgx/mod.rs
sgxs-tools/src/bin/sgxs-load.rs

* Add token-less EINIT ioctl
* Probe for device in two places

Changes to isgx loader

---

Cargo.toml
examples/.gitignore
examples/backtrace_panic/.cargo/config
examples/backtrace_panic/Cargo.lock
examples/backtrace_panic/Cargo.toml
examples/backtrace_panic/src/main.rs
examples/backtrace_panic/test.sh
examples/mpsc-crypto-mining/.cargo/config
examples/mpsc-crypto-mining/Cargo.lock
examples/mpsc-crypto-mining/Cargo.toml
examples/mpsc-crypto-mining/LICENSE
examples/mpsc-crypto-mining/readme.md
examples/mpsc-crypto-mining/src/main.rs
examples/tls/Cargo.lock
examples/tls/Cargo.toml
examples/tls/src/main.rs
examples/unit_tests/.cargo/config
examples/unit_tests/Cargo.lock
examples/unit_tests/Cargo.toml
examples/unit_tests/src/main.rs

Adding a few examples to rust-sgx which could be snippeted on our website after review.

Adding examples for x86_64-fortanix-unknown-sgx

---

scripts/gdb.py

sgx-add-symbol-file <ADDR_IN_ENCLAVE | auto> <ELF_PATH>
auto indicates address is to be read from rbx.
This fixes [#19](https://github.com/fortanix/rust-sgx/issues/19)

Adding a new gdb command to load enclave symbols.

---

enclave-runner/src/tcs.rs

See https://github.com/rust-lang/rust/issues/60450

Fix warning that appeared in latest nightly

---

sgx-isa/src/lib.rs

Added an inherent method that allows for local verification of the report

added verify to Report, replacing verify_report from libenclave

---

Cargo.lock
aesm-client/Cargo.toml
aesm-client/src/imp/unix.rs
aesm-client/src/imp/windows.rs
aesm-client/src/lib.rs
enclave-runner/src/usercalls/mod.rs
fortanix-sgx-tools/src/bin/ftxsgx-runner.rs
sgxs-loaders/Cargo.toml
sgxs-loaders/src/enclaveapi/mod.rs
sgxs-loaders/src/lib.rs
sgxs-loaders/src/sgx_enclave_common/mod.rs

This still requires a cargo update before it can build the runner

Win ftx runner

---

fortanix-sgx-tools/src/bin/ftxsgx-runner-cargo.rs

https://doc.rust-lang.org/std/process/struct.ExitStatus.html#method.code

Avoid panic if ftxsgx-runner is terminated by a signal

---

Cargo.lock
aesm-client/Cargo.toml
dcap-provider/Cargo.toml
dcap-ql/Cargo.toml
enclave-runner/Cargo.toml
fortanix-sgx-abi/Cargo.toml
fortanix-sgx-tools/Cargo.toml
report-test/Cargo.toml
rs-libc/Cargo.toml
sgxs-loaders/Cargo.toml
sgxs-tools/Cargo.toml
sgxs/Cargo.toml

Bumps versions in preparation for releasing crates

version bump in preparation for release

---

dcap-provider/README.md
dcap-ql/README.md
sgxs-loaders/src/sgx_enclave_common/mod.rs

Should really get some SGX-based CI in this repo...

Fix sgx-enclave-common loader, improve DCAP testing documentation

---

Cargo.lock
fortanix-sgx-tools/src/bin/ftxsgx-elf2sgxs.rs
sgxs/src/sgxs.rs
sgxs/src/sigstruct.rs

the following files were changed
fortanix-sgx-tools/src/bin/ftxsgx-elf2sgxs.rs
sgxs/src/sgxs.rs
sgxs/src/sigstruct.rs

Replace depricated item 'try!' with '?'

---

sgx-isa/Cargo.toml
sgx-isa/src/arch.rs
sgx-isa/src/lib.rs

I have solved the review comments. 
I am unsure of how the egetkey function would be used though

Pvs/no_std_nightly (Add nightly feature for no_std use of ereport function from libstd)

---

Cargo.lock
enclave-runner/Cargo.toml
enclave-runner/src/command.rs
enclave-runner/src/lib.rs
enclave-runner/src/loader.rs
sgxs/Cargo.toml
sgxs/src/crypto/mod.rs
sgxs/src/lib.rs

Allow using external crypto for dummy signature

---

Cargo.lock
enclave-runner/Cargo.toml
sgxs/Cargo.toml

Bump versions of sgxs and enclave-runner

---

fortanix-sgx-tools/src/bin/ftxsgx-elf2sgxs.rs

This pull request is related to [rust-lang pull request #67084](https://github.com/rust-lang/rust/pull/67084), which places the ELF entry point in a separate section of the ELF file. This pull request removes/overwrites that section during the conversion from ELF to SGXS, because that code is not needed in the enclave. To avoid changing the relative position of other code, the section is only removed if it is at the end of a program segment. It is overwritten with NOPs otherwise.
The pull request also includes some general refactoring of the code related to Splices.

elf2sgx: Remove .text_no_sgx section during conversion

---

enclave-runner/src/usercalls/mod.rs

when targeting musl, the rust libc crate does not have a compatible ucontext_t definition. (musl itself will provide one if _GNU_SOURCE is defined, but the libc crate does not do that.)
This change by itself does not result in a working musl build of the enclave runner, due to openssl build issues. When I add the "vendored" openssl feature, I am able to produce a working statically-linked musl build of the enclave runner.
I also tried building with the `rust:alpine` docker image, but that failed with proc macro build problems.

disable the debugger trap when building for musl

---

.travis.yml
sgxs-loaders/Cargo.toml

Adding all the tests which pass on Windows
As and when other tests pass, they can be added

Add Windows CI

---

enclave-runner/src/command.rs
enclave-runner/src/library.rs
enclave-runner/src/loader.rs
enclave-runner/src/usercalls/mod.rs

Add an EnclaveBuilder method to set a panic_on_abort flag.

eagerly print panics based on a new config option

---

aesm-client/src/imp/aesm_protobuf/mod.rs

It seems like each write turns into a separate enclave I/O, so, even if the helper service ought to be able to tolerate that, there is a small performance gain from combining them.

write entire request at once

---

enclave-runner/src/lib.rs
enclave-runner/src/tcs.rs
enclave-runner/src/usercalls/mod.rs
sgx-isa/src/arch.rs
sgx-isa/src/lib.rs
sgxs-tools/src/bin/sgxs-load.rs

asm! is not going to be supported soon, we need to move to llvm_asm!

Change asm! to llvm_asm!

---

enclave-runner/src/usercalls/mod.rs

`fn exit()` calling `abort_all_threads()` created a race condition:
return future in `fn syscall_loop()` would detect the exit and break
the syscall loop by receiving either the EnclaveAbort from the thread
that caused the exit or an EnclaveAbort::Secondary from other threads
that observed the exit in `fn dispatch()`.
To fix the issue:
- Avoid calling `abort_all_threads()` in `fn exit`. Do that only
after the syscall loop is broken.
- Ignore EnclaveAbort::Secondary from non-main threads in return
future which is not strictly needed after the previous change,
but would make the code easier to read.
Also, when a non-main thread calls `std::process::exit()` with any
exit status, it should terminate the enclave execution. This was
not handled correctly for exit status 0.

Fix exit bug

---

Cargo.lock
aesm-client/Cargo.toml
aesm-client/src/imp/aesm_protobuf/mod.rs
aesm-client/src/imp/windows.rs
aesm-client/src/lib.rs
aesm-client/tests/live_quote.rs
dcap-retrieve-pckid/Cargo.toml
dcap-retrieve-pckid/src/main.rs
fortanix-sgx-tools/Cargo.toml
sgxs-tools/Cargo.toml

* `QuoteInfo` isn't necessary for `get_quote`
* Make `get_quote_ex` more like `get_quote`
* Fix `get_quote_ex` return report value
* Add test for `get_quote_ex` with EPID

Clean up AESM client API

---

sgx-pkix/Cargo.lock
sgx-pkix/Cargo.toml

This reverts commit 66f29bdcafaa168a44bbd9162f25e1cb1ebf4035.

Revert "Update _ to -"

---

enclave-runner/src/usercalls/mod.rs
fortanix-sgx-abi/src/lib.rs

This should partially address issue #31

Allow arbitrary timeouts for wait usercall

---

enclave-runner/src/command.rs
enclave-runner/src/loader.rs
enclave-runner/src/usercalls/mod.rs
fortanix-sgx-tools/src/bin/ftxsgx-runner-cargo.rs
fortanix-sgx-tools/src/bin/ftxsgx-runner.rs

This should resolve issue #136

Pass arguments to executable enclaves

---

Cargo.lock

This should not change anything besides the `Cargo.lock` format.

Update Cargo.lock format

---

Cargo.lock
sgxs-loaders/Cargo.toml

Update sgxs-loaders version

---

Cargo.lock
enclave-runner/Cargo.toml
fortanix-sgx-abi/Cargo.toml
ipc-queue/Cargo.toml

Update fortanix-sgx-abi version

---

sgx-pkix/Cargo.toml

Forgot to do this with my previous change (https://github.com/fortanix/rust-sgx/pull/328)

bump version of sgx-pkix

---

Cargo.lock
sgxs-tools/Cargo.toml
sgxs-tools/src/sgx_detect/interpret.rs
sgxs-tools/src/sgx_detect/main.rs
sgxs-tools/src/sgx_detect/proc_macro.rs
sgxs-tools/src/sgx_detect/tests/mod.rs
sgxs-tools/src/sgx_detect/tests/scaffold.rs

`sgx-detect` support for confidentiality-only protection EPC

---

Cargo.lock
Cargo.toml
fortanix-vme/ci-common.sh
fortanix-vme/ci-fortanixvme.sh
fortanix-vme/fortanix-vme-abi/Cargo.toml
fortanix-vme/fortanix-vme-abi/src/lib.rs
fortanix-vme/fortanix-vme-runner/Cargo.toml
fortanix-vme/fortanix-vme-runner/src/lib.rs
fortanix-vme/tests/incoming_connection/Cargo.toml
fortanix-vme/tests/incoming_connection/out.expected
fortanix-vme/tests/incoming_connection/src/main.rs
fortanix-vme/tests/incoming_connection/test_interaction.sh

Enables the enclave to listen for incoming connections
This PR works together with [this rust PR](https://github.com/fortanix/rust/pull/3)

[plat-182] Inbound connections

---

Cargo.lock
rs-libc/Cargo.toml
rs-libc/README.md

- Update README
- Bump version number

rs-libc: prepare for publish new version of `rs-libc`

---

intel-sgx/scripts/gdb.py
intel-sgx/sgxs-loaders/src/generic.rs
intel-sgx/sgxs-loaders/src/isgx/debugging.rs
intel-sgx/sgxs-loaders/src/isgx/mod.rs

Fixes https://github.com/fortanix/rust-sgx/issues/488

Debugging Augusta loader with rust-gdb

---

intel-sgx/sgxs-loaders/src/sgx_enclave_common/defs.rs

Make `PageProperties` type FFI transparent

---

intel-sgx/sgxs/README.md

separating this as discussed in #529

sgxs: Update link to format specification

---

.idea/encodings.xml
em-app/src/lib.rs

This PR provides a functionality to compute a hash over the contents of application config.

Adds a function to compute hash over the contents of application config

---

Cargo.lock
intel-sgx/dcap-provider/Cargo.toml

- Bump dcap-provider version to 0.4.4

bump dcap-provider version

---

.github/workflows/build.yml

Document where the PCS_API_KEY came from

Document PCS_API_KEY

---

Cargo.lock
intel-sgx/dcap-artifact-retrieval/Cargo.toml
intel-sgx/pcs/Cargo.toml
intel-sgx/pcs/src/tcb_info.rs

Replicating changes in RTE-165

Remove potentially dangerous `Serialize` implementation for `TcbData`

---

intel-sgx/dcap-artifact-retrieval/src/cli.rs
intel-sgx/dcap-artifact-retrieval/src/lib.rs
intel-sgx/dcap-artifact-retrieval/src/main.rs
intel-sgx/dcap-artifact-retrieval/src/provisioning_client/azure.rs
intel-sgx/dcap-artifact-retrieval/src/provisioning_client/common.rs
intel-sgx/dcap-artifact-retrieval/src/provisioning_client/intel.rs
intel-sgx/dcap-artifact-retrieval/src/provisioning_client/mod.rs
intel-sgx/dcap-artifact-retrieval/src/provisioning_client/pccs.rs

dcap-artifact-retrieval: Implement provisioning client for PCCS

---

intel-sgx/scripts/gdb.py

Revert accidentally merged https://github.com/fortanix/rust-sgx/pull/697
Context: I accidentally merged the PR which is for testing

Revert accidentally merged test code 

---

.github/workflows/build.yml
Cargo.lock

* Update build github workflow to run on ubuntu 24.04
* Update mbedtls-sys-auto crate

Update build workflow to ubuntu 24

---

intel-sgx/pcs/src/pckid.rs

Improve pckid parse logic to handle empty lines.

[PROD-10400] Improve pckid parse logic

---

intel-sgx/dcap-artifact-retrieval/src/provisioning_client/azure.rs

The Azure dcap artifact retrieval tool wasn't being tested for the V4 api of the PCS service. This PR corrects that
Blocked by #811

[RTE-557] Ensure Azure is tested in V3 and V4

---

Cargo.lock
intel-sgx/dcap-ql-sys/Cargo.toml
intel-sgx/dcap-ql/Cargo.toml

Fix `ToPrimitive` and `FromPrimitive` warnings
Blocked by #811

[RTE-558] Fix ToPrimitive and FromPrimitive warnings
