doc/WINTEL-SGX-ABI.md
* fix cpuinfo bit table rendering
* correct a typo in "Enclave specificic: LE" heading
=> docs: wintel abi typesetting fixes

fortanix-sgx-tools/src/bin/ftxsgx-elf2sgxs.rs
The allocator (dlmalloc) used in `x86_64-fortanix-unknown-sgx` doesn't have this restriction.
=> Remove heap size check in elf2sgxs

sgx-isa/src/lib.rs
`Self::UNPADDED_SIZE` was passed as *count* for `copy_nonoverlapping` while copying objects of type `$name`.
We need to make sure copy_nonoverlapping copies bytes instead.
=> Fixing SIGSEV in copy_nonoverlapping.

enclave-runner/src/command.rs, enclave-runner/src/library.rs, enclave-runner/src/loader.rs, fortanix-sgx-tools/src/bin/ftxsgx-runner.rs, scripts/stack-trace-resolve, scripts/stack-trace-resolve.txt
1. Parse stack trace from stored output:
stack-trace-resolve [-o <opt>] [-s] -e <executable_path> -f <stack_trace_file>
2. Parse stack trace from output of an enclave over pipe:
<output_stream> | stack-trace-resolve [-o <opt>] [-s] -e <executable_path>
3. Paste stack trace prints from an output in raw mode.
stack-trace-resolve [-o <opt>] [-s] -e <executable_path> -r
1. -o <opt>:
This option lets user customize the output format of the stack trace translation.
Here, opt indicates options passed to addr2line, default being [default: -Cfp].
Please refer to manpage of addr2line for further details about options.
2. -s:
This option suppresses the output that does not pertain to stack trace.
Without -s, lines of output before and after the stack trace would be echoed on the screen.
3. -r:
This …
=> Script to parse rust-sgx backtrace.

Cargo.lock, fortanix-sgx-tools/Cargo.toml, fortanix-sgx-tools/src/bin/ftxsgx-runner-cargo.rs
This script encapsulates the three steps listed [here](https://github.com/fortanix/rust-sgx/issues/49) under `Running`.
To trigger this script on `cargo run`, add .cargo/config file within crate with content:
> [target.x86_64-fortanix-unknown-sgx]
> runner = "ftxsgx-runner-cargo"
And to set custom values for arguments to `ftxsgx-elf2sgxs` script, add `package.metadata` section in Cargo.toml
> [package.metadata]
> threads=15
=> runner script

fortanix-sgx-tools/src/bin/ftxsgx-elf2sgxs.rs, fortanix-sgx-tools/src/bin/ftxsgx-runner-cargo.rs
`elf2sgxs` used to generate unsized enclaves that would need to be appended using `sgxs-append`. This is a niche use case. Instead, generate sized enclaves by default so that appending is unnecessary. Add a command line option to `elf2sgxs` to generate an unsized enclave instead.
=> Make sized enclaves by default

Cargo.lock, enclave-runner/Cargo.toml, enclave-runner/src/lib.rs, enclave-runner/src/usercalls/mod.rs, scripts/gdb.py
With this chage, To get a back trace in case of an abort, the user has to source gdb.py and,
call `sgxstate auto [<executable path>]`
1. It needs tcs address to be present in rbx register.
2. It calls `sgxstate tcs $rbx`
3. We can optionally provide path to the executable, in which case it will load the symbols.
In case of a panic, the enclave-runner would raise sigtrap with tcs address in Rbx.
In case there is no gdb attached, the runner's signal handler will continue execution.
=> Enhancing gdb.py script to show backtrace for an abort.

enclave-runner/src/usercalls/interface.rs, fortanix-sgx-abi/src/lib.rs
This matches Linux/Windows behavior
=> Clarify behavior around reading/writing zero-length buffers.

.travis.yml
This reverts commit b30f2f24bbf86a3d4ca979804084757064499f73.
=> Revert "Anchor Intel package versions until upstream is fixed"

Cargo.lock, doc/SGXS.md, sgxs-loaders/src/enclaveapi/mod.rs, sgxs/src/sgxs.rs
Removed the wrong check in the `add` function in enclaveapi sgxs-loader
Added a check in CanonicalSgxsReader to ensure that the TCS Page does not have any page permission flags set
Closes #146
=> Fixed TCS permissions for Windows

Cargo.lock, enclave-runner/Cargo.toml, enclave-runner/src/command.rs, enclave-runner/src/library.rs, enclave-runner/src/loader.rs, enclave-runner/src/tcs.rs, enclave-runner/src/usercalls/interface.rs, enclave-runner/src/usercalls/mod.rs, examples/usercall-extension/test.sh
Cleaned up code + Did some Error checking
Added in debug statements (using eprintln!)
TODO:
remove the previous main_entry function and related functions
find best way to select numer of worker threads
find a way to make current arch work in library mode
need to fine tune some Error handling
1) bail! wont work (because of crossbeam scope requiring a different return type??)
2) need to  send an error handling message to the usercall thread if "The enclave returned from the main entrypoint in violation of the specification"
3) need to do something about populationg `cmddata.other_reasons`
4) need to be able to read 'cmddata.primary_panic_reason'
=> WIP arch change async io : synchronous impl

Cargo.lock, aesm-client/Cargo.toml, aesm-client/build.rs
Updating protobuf crate version in order to fix [CVE-2019-15544](https://nvd.nist.gov/vuln/detail/CVE-2019-15544)
This also needs a corresponding update in protoc compiler.
=> Updating protobuf version to fix CVE-2019-15544

sgxs/src/sgxs.rs
`an_array.into_iter()` currently just works because of the autoref
feature, which then calls `<[T] as IntoIterator>::into_iter`. But
in the future, arrays will implement `IntoIterator`, too. In order
to avoid problems in the future, the call is replaced by `iter()`
which is shorter and more explicit.
A crater run showed that your crate is affected by a potential future 
change. See https://github.com/rust-lang/rust/pull/65819 for more information.
=> Use `slice::iter` instead of `into_iter` to avoid future breakage

fortanix-sgx-tools/src/bin/ftxsgx-runner-cargo.rs
remove `--signature dummy` (to allow operations with runners that do not
implement it) because it is anyways the default in ftxsgx-runner
=> add an option to override the runner

Cargo.lock
The build currently fails because rust-lld cannot find libgcc. The latest rust-mbedtls no longer depends on libgcc.
=> Update mbedtls dependency to latest version

Cargo.lock, examples/tls/Cargo.toml, examples/tls/src/main.rs, sgx-isa/Cargo.toml
Also fix a small deprecation warning in the `tls` example.
As far as I can tell we do not have other github deps anywhere in the repo.
=> Replace a github dep on mbedtls with crates.io

Cargo.lock, dcap-ql/Cargo.toml, dcap-ql/src/quote.rs, sgx-isa/Cargo.toml, sgx-isa/src/lib.rs
This PR is meant to provide `serde` support to serialize and deserialize Quote, Report, and Targetinfo structs if the (new) "serde_support" feature is enabled.
=> Quote serde

Cargo.lock, aesm-client/Cargo.toml, dcap-provider/Cargo.toml, dcap-ql/Cargo.toml, enclave-runner/Cargo.toml, fortanix-sgx-tools/Cargo.toml, report-test/Cargo.toml, sgxs-tools/Cargo.toml
Here's the order for publishing on crates.io:
1. minor bumps:
- `enclave-runner`
2. minor bumps:
- `fortanix-sgx-tools`
- `report-test`
3. minor bumps:
- `sgxs-tools`
4. minor bumps:
- `dcap-provider`
5. patch bumps:
- `aesm-client`
- `dcap-ql`
=> Bump up versions for async runner

Cargo.lock, aesm-client/Cargo.toml, aesm-client/src/imp/unix.rs, aesm-client/src/imp/windows.rs, aesm-client/src/lib.rs, aesm-client/tests/live_quote.rs, fortanix-sgx-tools/Cargo.toml, sgxs-tools/Cargo.toml
- extended the `get_quote` function with quote type and nonce
- bumped aesm-client version to 0.4 (as function params changed)
and *-tools patch version (as nothing changed in them,
except for using a new version of aesm-client)
=> more flexible get_quote in aesm-client (fixes #116 and #113)

.travis.yml, aesm-client/src/imp/aesm_protobuf/mod.rs, aesm-client/src/imp/sgx.rs, aesm-client/src/imp/unix.rs, aesm-client/src/imp/windows.rs, aesm-client/src/lib.rs
The implementation of AESM for SGX takes in a TcpStream for its constructor.
It omits the get_launch_token functionality
=>  Add implementation of AESM client for SGX 

fortanix-sgx-tools/src/bin/ftxsgx-elf2sgxs.rs
LVI mitigations require the first enclave page to not be executable.
https://software.intel.com/security-software-guidance/insights/deep-dive-load-value-injection#adhocLBmitigation
=> Check enclave page 0 is not executable

enclave-runner/src/usercalls/mod.rs
=> Enable enclave exit when a TCS is blocked on I/O

fortanix-sgx-tools/src/bin/ftxsgx-elf2sgxs.rs
Changes are needed to:
1. Allow libunwind update.
- We now have 4 symbols to reference start and size of sections .eh_frame and .eh_frame_hdr
- We need to support previous versions as well.
- Symbols are not reused from previous version to cause failure at compile time if old tool is used with new libunwind. (also added version check code to prevent this issue in the future and provide nice messages)
2. Fail gracefully if toolchain version is unsupported (give user a nice message telling to update tools)
=> Libunwind update + toolchain verification

aesm-client/src/imp/aesm_protobuf/mod.rs, aesm-client/src/imp/unix.rs, aesm-client/src/lib.rs
Fixes bug where calls to aesm from sgx module hangs indefinitely
Also make imported failure crate public
=> aesm-client: Add timeout values to send to quoting enclave for sgx

rs-libc/LICENSE, rs-libc/src/c/memrchr.c, rs-libc/src/c/strrchr.c
This is useful for compiling sqlite3. The functions were swiped from [musl](https://git.musl-libc.org/cgit/musl/tree/src/string/memrchr.c), like the rest of them.
=> Add strrchr to rs-libc

Cargo.lock, doc/FORTANIX-SGX-ABI.md, doc/FORTANIX-SGX-ELF.md, fortanix-sgx-tools/Cargo.toml
Updated both fortanix-sgx-tools and aesm-client versions
=> Update version due to libunwind update

Cargo.lock, aesm-client/Cargo.toml, dcap-provider/Cargo.toml, dcap-ql/Cargo.toml, dcap-retrieve-pckid/Cargo.toml, doc/FORTANIX-SGX-ABI.md, enclave-runner/Cargo.toml, fortanix-sgx-tools/Cargo.toml, report-test/Cargo.toml, rs-libc/Cargo.toml, sgx-isa/Cargo.toml, sgxs-loaders/Cargo.toml, sgxs-tools/Cargo.toml
Planning to release:
* rs-libc 0.2.1
* sgx-isa 0.3.2
* sgxs-loaders 0.2.2
* enclave-runner 0.4.0
* report-test 0.3.1
* dcap-ql 0.3.0
* aesm-client 0.5.0
* dcap-provider 0.3.1
* sgxs-tools 0.8.2
* fortanix-sgx-tools 0.4.0
* dcap-retrieve-pckid 0.1.0
(in that order)
=> Bump crate versions for publication

doc/rust-std-edp-doc.patch, sgxs-tools/src/bin/isgx-pe2sgx.rs
replaced rust-std-edp-doc.patch with a newer version
The doc generation failed because the patch could not be applied.
=> Fix doc generation

aesm-client/Cargo.toml, dcap-ql/Cargo.toml, dcap-retrieve-pckid/Cargo.toml, fortanix-sgx-tools/Cargo.toml, sgxs-tools/Cargo.toml
Based on this dependency graph generated with `cargo depgraph  --all-deps --focus sgxs-loaders | dot -Tpng > graph.png`:
I have bumped the patch versions of all workspace members that directly depend on sgxs-loaders
=> Bump dependents of sgxs-loaders

Cargo.lock, sgx-isa/Cargo.toml, sgx-isa/src/lib.rs, sgxs-tools/src/sgx_detect/tests/mod.rs
Adds support to `sgx-detect` to determine if the platform supports KSS (ref #200)
=> Add KSS detection to sgx-detect

sgxs-loaders/src/enclaveapi/mod.rs, sgxs-loaders/src/generic.rs, sgxs-loaders/src/isgx/mod.rs, sgxs-loaders/src/sgx_enclave_common/mod.rs
Avoid running into the `/proc/sys/vm/max_map_count` limit by creating fewer larger mappings instead of mapping every page.
This unfortunately requires delaying the last `mmap` call to `einit` time, which is not great UX. This is the same as what Intel does in their SDK though.
=> Augusta SGX loader: map contiguous similar pages at once

enclave-runner/Cargo.toml, enclave-runner/src/usercalls/mod.rs
The elusive memory leak that I was chasing was not an actual leak, but was rather caused by pile up of events broadcast to all TCS's. This PR fixes the issue by removing the unbounded channel used for events.
=> Limit memory usage for broadcast events

.travis.yml
Remove `-Z package-features` from the Travis CI config after its stabilization with https://github.com/rust-lang/cargo/pull/8997
=> Remove unstable package-features after stabilization

em-app/Cargo.toml, em-app/src/lib.rs
the CsrSigner trait is similar to ExternalKey, but instead of allowing signing of arbitrary messages, only signs CSRs.
a default implementation of CsrSigner is provided for anything that implements ExternalKey
=> add a CsrSigner trait to em-app

Cargo.lock, dcap-ql/Cargo.toml
Updates `dcap-ql` to `mbedtls` 0.7.0 and `mbedtls-sys` to 2.25.1.
cc: @jethrogb
=> Update `dcap-ql` to `mbedtls` 0.7.0

em-app/Cargo.lock, em-app/Cargo.toml
Commit https://github.com/fortanix/rust-sgx/pull/312/commits/edc4444f39cc7f709f7c80ba508d1a09c163d0c7 inadvertently bumped the version of `em-app`. This PR reverts that change.
=> Reverting version bump em-app

.travis.yml, Cargo.lock, aesm-client/Cargo.toml, aesm-client/src/lib.rs
`aesm-client` could not get build with `sgx-isa/sgxstd` feature
=> `aesm-client` bug fix

rs-libc/build.rs
Currently the directory listing order in rs-libc's build.rs is non-deterministic, and this order is fed into the `cc` build directly, making the final binary artifact non-reproducible. This is because link-time relocation is dependent on the order in which inputs are specified.
In certain use-cases of SGX the attested measurement must be reproducible by third parties, otherwise a security audit of the enclave code cannot be tied to attestations.
The fix is to simply sort the listing.
=> rs-libc: Fix build determinism

aesm-client/Cargo.toml, aesm-client/src/imp/aesm_protobuf/mod.rs, aesm-client/src/lib.rs
This should fix #179.
Quoting from that issue:
> When aesmd is still unprovisioned, AesmClient::init_quote() triggers EPID provisioning, and in this case the client returns an AesmCommunication error.
=> Use remote instead of local timeout for init_quote() in aesm-client

Cargo.lock
Forgot to add this file to the PR that bumps the aesm-client version.
=> Update Cargo.lock after aesm-client version bump

enclave-runner/src/tcs.rs, enclave-runner/src/usercalls/mod.rs
LLVM reserves register `rbx` in inline assembly (issue: #335). This PR avoids the use of this register until [rust-lang issue 85056](https://github.com/rust-lang/rust/issues/85056) is merged
=> Avoiding use of LLVM reserved register `rbx`

rs-libc/build.rs
Hello, for our build system we use `nix` specifically `naersk` (https://github.com/nmattia/naersk).
During the building process dependencies are linked into a build dir, not copied.
The `rs-libc` build script explicitly checks that the dir entries are files, so symlinks get ignored.
One possible solutions for our use case would be to remove this check.
=> rs-libc: resolve symlinks in build script

doc/rust-std-edp-doc.patch
The directory structure of the rust compiler changed upstream. We apply a patch before generating documentation for the sgx target. This patch needs an update to reflect the new directory structure.
=> Update documentation patch to new rust folder structure

Cargo.lock, Cargo.toml, fortanix-vme/ci-common.sh, fortanix-vme/ci-fortanixvme.sh, fortanix-vme/fortanix-vme-abi/src/lib.rs, fortanix-vme/fortanix-vme-runner/src/lib.rs, fortanix-vme/tests/iron/Cargo.toml, fortanix-vme/tests/iron/out.expected, fortanix-vme/tests/iron/src/main.rs, fortanix-vme/tests/iron/test_interaction.sh
Nitro enclaves can bind to a `TcpListener` in the runner. Incoming `TcpStream` connections will be forwarded to the enclave. When the client terminates its connections, the proxy connection in the runner need to be terminated as well.
=> Ensure incoming `TcpStream` connections are closed

fortanix-vme/fortanix-vme-abi/src/lib.rs, fortanix-vme/fortanix-vme-runner/src/lib.rs, fortanix-vme/tests/incoming_connection/src/main.rs
`TcpStream`s and `TcpListener`s need to be able to return the address of the remote party. This PR:
* Makes the runner return the peer address when a new connection is established
* Returns the full address (not just the port) when a `Bound` response is send to the enclave
* Adds a test for this functionality
* Adds a statement ensuring warnings are treated as errors
=> Storing peer address

Cargo.lock, Cargo.toml, fortanix-vme/ci-common.sh, fortanix-vme/ci-fortanixvme.sh, fortanix-vme/eif-tools/src/bin/ftxvme-elf2eif.rs, fortanix-vme/tests/hello_world/Cargo.toml, fortanix-vme/tests/hello_world/src/main.rs, fortanix-vme/tests/outgoing_connection/src/main.rs
The `ftxvme-elf2eif` used to generate eif files based on the `scratch` Docker image. That is causing problems for Nitro enclaves. Reverted back to the `alpine` image for now. CI has also been modified to facilitate easier testing in the future.
=> [PLAT-388] Bugfix `ftxvme-elf2eif`

Cargo.lock, fortanix-vme/fortanix-vme-abi/src/lib.rs, fortanix-vme/fortanix-vme-runner/src/lib.rs
TcpListeners are being stored by the stdlib in a list together with the file descriptor used for them in the runner. That is suboptimal. A recent change enabled storing additional data in the Socket. That enables to get rid of this linked list. However, for that to work we need to reference TcpListeners with the port they are bound to, not their file descriptor in the runner. This PR performs the required interface changes.
[rust PR12](https://github.com/fortanix/rust/pull/12) pulls in the required changes in the standard library
=> [PLAT-397] Refactoring keeping track of `TcpListeners`

Cargo.lock, fortanix-vme/fortanix-vme-runner/src/lib.rs, fortanix-vme/fortanix-vme-runner/src/main.rs
This PR improves on two key areas:
- Information about TCP connections are stored in a hashmap, similar to how information about TCP server sockets is tracked. This will enable this information to be requested from the enclave in a subsequent PR
- The way how connections are proxied, is modified. Instead of starting another thread per TCP connection, a single proxy thread is started. It iterates over all TCP connections and exchanges message once for each connection. When no connections are currently available, the thread yields its CPU time.
=> [PLAT-396] Refactor threads

fortanix-vme/ci-common.sh, fortanix-vme/fortanix-vme-abi/src/lib.rs, fortanix-vme/fortanix-vme-runner/src/lib.rs, fortanix-vme/tests/incoming_connection/out.expected, fortanix-vme/tests/incoming_connection/src/main.rs, fortanix-vme/tests/incoming_connection/test_interaction.sh
When a Nitro enclave closes a `TcpListener`, sockets in the runner need to be cleaned up as well. This PR introduces the required changes to the ABI and runner.
=> Closing `TcpListeners` in runner

fortanix-vme/tests/iron/src/main.rs
Remove non-stable features so CI can move to stable rust compiler 1.59 once that lands.
=> [PLAT-423] Avoid non-stable feature

fortanix-vme/fortanix-vme-abi/src/lib.rs, fortanix-vme/fortanix-vme-runner/src/lib.rs, fortanix-vme/tests/incoming_connection/src/main.rs
When `TcpListener`s or `TcpStream`s are created from a `RawFd`, they lack information about local and/or peer ports used in the runner. When this information is requested, it needs to be fetched from the runner.
=> [PLAT-367] Connection info

Cargo.lock, fortanix-vme/eif-tools/Cargo.toml, fortanix-vme/eif-tools/src/bin/ftxvme-runner-cargo.rs
Currently, to spawn an enclave, one has to do the following 3 steps:
- Convert elf to eif
- (not always required) Start fortanix-vme-runner which is basically a vsock proxy
- nitro-cli run-enclave
This PR adds code for a [custom runner for target `x86_64-unknown-linux-fortanixvme`](https://doc.rust-lang.org/cargo/reference/config.html#targettriplerunner) which will automate the above steps. This is pretty much like `ftxsgx-runner-cargo`. Although, I haven't created a separate `ftxvme-runner` like `ftxsgx-runner` as we can use `nitro-cli` directly here.
This runner spawns `fortanix-vme-runner` (this can be disabled by options in metadata) but doesn't wait on it. So, it doesn't know its exit status. If `fortanix-vme-runner` has been spawned before, it will not cause issues for the runner as …
=> [PLAT-351]: Support an easy way to run Nitro enclaves

Cargo.lock, Cargo.toml
remove em-client patch since we now have a released version on crates.io
=> Remove em-client patch

fortanix-vme/aws-nitro-enclaves/tests/incoming_connection/out.expected, fortanix-vme/aws-nitro-enclaves/tests/incoming_connection/src/main.rs, fortanix-vme/aws-nitro-enclaves/tests/outgoing_connection/out.expected, fortanix-vme/aws-nitro-enclaves/tests/outgoing_connection/src/main.rs, fortanix-vme/aws-nitro-enclaves/tests/outgoing_connection/test_interaction.sh, fortanix-vme/ci-common.sh
An enclave should be able to bind a TCP listener on `localhost`. Likewise, it should be able to establish a local connection to the parent VM. Before this PR both scenarios worked correctly, but CI tests were missing.
=> [PLAT-268] Test connecting to and binding on `localhost`

.travis.yml, Cargo.lock, em-app/Cargo.toml, fortanix-vme/tests/incoming_connection/src/main.rs, intel-sgx/enclave-runner/src/lib.rs, intel-sgx/enclave-runner/src/tcs.rs, intel-sgx/enclave-runner/src/usercalls/mod.rs, intel-sgx/sgx-isa/Cargo.toml, intel-sgx/sgx-isa/src/arch.rs, intel-sgx/sgx-isa/src/lib.rs, intel-sgx/sgx_pkix/Cargo.toml, intel-sgx/sgxs-tools/src/bin/sgxs-load.rs
Once Rust 1.59 is released, this needs to be merged, minor versions need to be bumped where appropriate, and this should be released.
=> Switch to stable asm!

Cargo.lock, em-app/Cargo.toml, intel-sgx/aesm-client/Cargo.toml, intel-sgx/dcap-ql-sys/Cargo.toml, intel-sgx/dcap-ql/Cargo.toml, intel-sgx/dcap-retrieve-pckid/Cargo.toml, intel-sgx/enclave-runner/Cargo.toml, intel-sgx/fortanix-sgx-abi/Cargo.toml, intel-sgx/fortanix-sgx-tools/Cargo.toml, intel-sgx/report-test/Cargo.toml, intel-sgx/sgx-isa/Cargo.toml, intel-sgx/sgx_pkix/Cargo.toml, intel-sgx/sgxs-loaders/Cargo.toml, intel-sgx/sgxs-tools/Cargo.toml, intel-sgx/sgxs/Cargo.toml, ipc-queue/Cargo.toml
In order to publish crates, some crates' version numbers need to be bumped. The following crates can/should be published:
- em-app
- fortanix-sgx-abi
- aesm-client
- dcap-ql-sys
- dcap-ql
- dcap-retrieve-pckid
- enclave-runner
- fortanix-sgx-tools
- report-test
- sgx-pkix
- sgxs-loaders
- sgxs-tools
- sgxs
- ipc-queue
=> Preparing crate publications

ipc-queue/src/fifo.rs
When processing `FifoDescriptor` to turn it into a `ipc_queue`, the offset point isn't verified correctly.
=> [PLAT-896] Verify fifo descriptor pointers

ipc-queue/src/fifo.rs, ipc-queue/src/interface_async.rs, ipc-queue/src/interface_sync.rs, ipc-queue/src/lib.rs
=> [PLAT-838] Refactor `ipc_queue` backport

Cargo.lock, intel-sgx/enclave-runner/Cargo.toml, intel-sgx/fortanix-sgx-abi/Cargo.toml, intel-sgx/fortanix-sgx-abi/src/lib.rs, ipc-queue/Cargo.toml
We need to publish `fortanix-sgx-abi` with this change and then update libstd's dependency on `fortanix-sgx-abi` so we can remove the hacks in #404.
=> Add cancel queue to SGX ABI

intel-sgx/fortanix-sgx-abi/src/lib.rs
Document that a TCS struct should never be located as the beginning of an enclave. (ref https://github.com/rust-lang/rust/pull/98391)
=> Document `TCS` struct limitations

Cargo.lock, intel-sgx/ias/Cargo.toml
We never released any version. So it should be 0.1.0.
=> Fix IAS crate version

Cargo.lock, em-app/Cargo.toml, intel-sgx/ias/Cargo.toml, intel-sgx/sgx_pkix/Cargo.toml
sgx_pkix version 0.1.2 was incorrectly numbered. This version changed the version of sgx-isa used, which in turn changed the version of the mbedtls dependency. mbedtls 0.8.0 is not compatible with version 0.7.0, so version 0.1.2 is not compatible with code that was using 0.1.1. This release should have been numbered 0.2.0.
Two other crates directly depend on sgx_pkix: em-app and ias. I've updated their dependencies, and bumped the third digit in their versions. We will want to yank sgx_pkix version 0.1.2,  em-app version 3.0, and ias version 1.0 when the new versions are published.
=> Change sgx_pkix crate version to 0.2.0. EDP-99.

em-app/Cargo.lock, em-app/Cargo.toml
This PR is similar to #420, but is for `em-app` instead of `sgx_pkix`.
=> Indicate that em-app 0.2.1 is compatible with pkix v0.1.x and v0.2.x.

.travis.yml
Now that the `em-app_v0.2.x` branch has been marked as a protected branch, `bors` is enabled on it. The `.travis.yml` file on that branch doesn't have the `staging` or `trying` branches listed, which means CI won't be started for those branches and `bors` will time out on `bors r` and `bors try` commands. This PR attempts to fix that by adding those branches to the `.travis.yml` file.
=> Fix bors on em-app_v0.2.x branch

em-app/Cargo.lock, em-app/Cargo.toml, em-app/src/lib.rs
This PR adds the `get_certificate()` function that is available in `em-app 0.3` to `em-app 0.2` in a backwards-compatible way.
=> Backport get_certificate() function from em-app 0.3 to em-app 0.2.

.travis.yml
Same as #427, but now for the `sgx-pkix_v0.1.x` branch.
Now that the `sgx-pkix_v0.1.x` branch has been marked as a protected branch, bors is enabled on it. The `.travis.yml` file on that branch doesn't have the `staging` or `trying` branches listed, which means CI won't be started for those branches and bors will time out on `bors r` and `bors try` commands. This PR attempts to fix that by adding those branches to the `.travis.yml` file.
=> Fix bors on sgx-pkix_v0.1.x branch

Cargo.lock, intel-sgx/dcap-retrieve-pckid/Cargo.toml, intel-sgx/dcap-retrieve-pckid/src/lib.rs, intel-sgx/dcap-retrieve-pckid/src/main.rs
Split the origin code in `dcap-retrieve-pckid` into `lib.rs` and `main.rs`
So that this code could be easy reuse elsewhere.
=> refactor dcap-retrieve-pckid

.travis.yml, dcap-ql/src/bindings/mod.rs
The `aesmd` service depends on a `dcap_quoteprov.so` library (the DCAP provider) to aid in DCAP attestations. For it to work correctly, it may need to (recursively) request a DCAP attestation itself. For that a `dcap-ql::enclave_loader` call is required. Unfortunately, when this happens as part of the `aesmd` service, `Dl::this()` returns `/opt/intel/sgx-aesm-service/aesm/aesm_service`. This leads to an error as the expected symbols can't be located. This PR adds a fallback to the `libsgx_enclave_common.so.1` library (or `sgx_enclave_common.dll` on windows).
=> Enable `enclave_loader()` fallback to libsgx_enclave_common.so.1

intel-sgx/dcap-ql/src/bindings/mod.rs
The aesmd service depends on a dcap_quoteprov.so library (the DCAP provider) to aid in DCAP attestations. For it to work correctly, it may need to (recursively) request a DCAP attestation itself. For that a `dcap-ql::enclave_loader` call is required. Unfortunately, when this happens as part of the aesmd service, `Dl::this()` returns `/opt/intel/sgx-aesm-service/aesm/aesm_service`. This leads to an error as the expected symbols can't be located. This PR adds a fallback to the `libsgx_enclave_common.so.1` library (or `sgx_enclave_common.dll` on windows).
This commit has been merged already on a different branch as part of #432
=> Enable `enclave_loader()` fallback to `libsgx_enclave_common.so.1`

.travis.yml, Cargo.lock, em-app/Cargo.lock, em-app/Cargo.toml, sgx-pkix/Cargo.toml, sgx-pkix/src/lib.rs, sgx-pkix/src/oid.rs
Attestation transparency information will be added to the certificate used for joining the cluster, so we need an OID for that purpose.
This is being added on the 1.x branch because roche currently must be built with a 1.x version of sgx_pkix due to dependencies on dcap-ql version 3.3. dcap-ql can't be updated without updating mbedtls.
=> Add an OID for attestation transparency. HRST-32

.travis.yml, Cargo.lock, intel-sgx/sgxs-tools/Cargo.toml, intel-sgx/sgxs-tools/README.md, intel-sgx/sgxs-tools/src/deprecated/isgx-pe2sgx.rs
Fix #433 by removing `isgx-pe2sgx` in CI
If it's not used, maybe we could also remove the code.
Please correct me if it's actively used somewhere
=> fix pe error by removing `isgx-pe2sgx` in CI

Cargo.lock, intel-sgx/sgx_pkix/Cargo.toml, intel-sgx/sgx_pkix/src/lib.rs, intel-sgx/sgx_pkix/src/oid.rs
This adds an X509 OID for attestation transparency. This change was previously made ont he sgx_pkix 0.1.x branch (for sgx_pkix version 0.1.4). This change adds the new OID on the master branch for sgx_pkix version 0.2.2, for when we migrate roche to the latest releases of the crates that belong to rust-sgx.
=> X509 OID for attestation transparency for sgx_pkix. HRST-33.

.travis.yml
Fixes https://github.com/fortanix/rust-sgx/issues/458
Learnings from fixing the issue:
- Travis Ubuntu "patch" upgrade (20.04.5 -> 20.04.6) can cause a major upgrade of certain libraries, such as clang version 7 -> clang version 16. After a lot of tinkering and local tests, we were able to identify this as the root cause
- TravisCI seems to install its binaries (such as clang) not as an Apt package but directly in `/usr/local`. One should be aware that there's no simple package to uninstall this way, and the very dirty solution of `rm -rf /usr/local/clang-16` might be needed.
- clang can work perfectly... even when `clang --version` fails
- We've discovered an underlying issue with our build that caused breakage from simply the *presence* of a newer clang, even if the desired clang-11 is …
=> Fix CI breakage

README.md
The old page is 404 Not Found.
=> docs: fix the link to Travis CI

Cargo.lock, intel-sgx/dcap-ql/Cargo.toml
This PR upgrade `dcap-ql`'s dependency on `mbedtls` to `0.9`
Note: what `mbedtls` API used by `dcap-ql` is not changed in both 0.8 and 0.9, so I use version range to accept both minor version.
This PR also is one step to upgrade `mbedtls` dependency in `rust-sgx` to next major release `0.10.0` which support TLS 1.3
:boom: After this PR is merged, new version of  `dcap-ql` need to be published!!
=> Upgrade dcap-ql to accept mbedtls 0.9

Cargo.lock, rs-libc/Cargo.toml, rs-libc/build.rs, rs-libc/src/alloc.rs, rs-libc/src/lib.rs
See https://github.com/fortanix/rust-mbedtls/pull/278
We need  `explicit_bzero` in `libc` in SGX
=> feat: add implementation of `explicit_bzero` in `rs-libc`

Cargo.lock, intel-sgx/dcap-ql/Cargo.toml
A typo in the specification of the `mbedtls` dependency of `dcap-ql` may lead to a compilation error.
Fixes #497
cc: @Taowyoo @jethrogb @vn971 @mkaynov
=> Fix typo in `dcap-ql` dependency

Cargo.lock, intel-sgx/enclave-runner/Cargo.toml, intel-sgx/enclave-runner/src/loader.rs
When calling the enclave main first argument must be always initialized
Resolves #386
=> Initialize enclave args with the first argument

intel-sgx/sgxs-loaders/src/generic.rs, intel-sgx/sgxs-loaders/src/isgx/mod.rs
Currently, the enclave's baseaddress is registered in a different module than where it is unregistered. This is error-prone.
=> Group enclave baseaddress un/registration together

Cargo.lock
* Errors in rust-lang tests with fortanix-sgx-tools built from sources:
```
11:29:23 ---- net::tcp::tests::bind_error stdout ----
11:29:23 thread 'net::tcp::tests::bind_error' panicked at 'assertion failed: `(left == right)`
11:29:23   left: `InvalidInput`,
11:29:23  right: `AddrNotAvailable`', library/std/src/net/tcp/tests.rs:29:19
```
* They come from this tokio line:
https://github.com/tokio-rs/tokio/blob/tokio-0.2.22/tokio/src/net/tcp/listener.rs#L138
* net2 and mio tokio's dependencies updated in lock file to solve this
Resolves #504
=> Update mio net2 deps in cargo.lock

.travis.yml
CI builds `fortanix-sgx-tools` for the `x86_64-unknown-linux-musl` target by linking a glibc version of openssl. This likely never resulted in runnable executables, but only recently resulted in missing symbol issues. This PR "fixes" this issue by ignoring the linking step altogether. 
Fixes #516 
Opened #518 for a proper fix (if we even want to support the platform properly)
=> Fix CI issue with `x86_64-unknown-linux-musl` target

em-app/src/csr.rs, em-app/src/lib.rs, em-app/src/platform/mod.rs, em-app/src/platform/nitro.rs, em-app/src/platform/sgx.rs
In light of recent requirements to be able to request certificates with no Common Name (as this is deprecated), this change creates versions of several functions that accept a `Name`  as a parameter instead of a common name string. In this case, the user will be able to provide an empty `Name`, where the internal value is an empty `Vec`. In order to provide backwards compatibility, the existing functions that use common name have not been changed.
=> Added version of certificate request functions that accept Subject as parameter

intel-sgx/aesm-client/src/imp/aesm_protobuf/mod.rs, intel-sgx/aesm-client/src/imp/sgx.rs, intel-sgx/aesm-client/src/imp/unix.rs
Fixes error due to unused import in `aesm-client`.
Fixes #537
=> Remove unused import

intel-sgx/sgxs-tools/src/bin/sgxs-info.rs
Replace the use of `stdout().write(&data)` with `stdout().write_all(&data)` to always ensure complete data writes.
The original code would silently continue even after the data buffer was only partially written, producing incomplete and buggy SGXS memory dumps in practice.
See also:
* https://doc.rust-lang.org/std/io/trait.Write.html#tymethod.write
* https://doc.rust-lang.org/std/io/trait.Write.html#method.write_all
This can be easily observed, e.g., as follows already in the 2nd page of an EDP-generated SGXS:
```
$ sgxs-info summary hello-world.sgxs 
0-   efff Reg  r--  (data) meas=all
f000-  34fff Reg  r-x  (data) meas=all
...
```
Before the fix in this PR the executable page is _not_ entirely copied into the memory dump (the last 1446 bytes are silently skipped and are filled in by the …
=> sgxs-info: Fix bug with incomplete data writes in dump-mem

Cargo.lock, intel-sgx/dcap-provider/Cargo.toml, intel-sgx/dcap-provider/src/lib.rs, intel-sgx/sgxs-tools/Cargo.toml, intel-sgx/sgxs-tools/src/sgx_detect/main.rs, intel-sgx/sgxs/Cargo.toml, intel-sgx/sgxs/src/sigstruct.rs
=> Update time crate

Cargo.lock, intel-sgx/enclave-runner/Cargo.toml, intel-sgx/enclave-runner/src/usercalls/interface.rs, intel-sgx/enclave-runner/src/usercalls/mod.rs, ipc-queue/Cargo.toml, ipc-queue/src/interface_async.rs
The next step to get the async I/O work fully upstreamed: updating the enclave runner to the latest version of tokio.
=> Update tokio dependency of enclave runner

em-app/Cargo.toml
The `em-app` is compatible with `pkix` v0.1.3 and v0.2.x. The `pkix` crate was bumped to v0.2 [only due](https://github.com/fortanix/pkix/commits/master/?after=bdda1b505e7b13cbb7c5e7a6c0ad696f71917ecd+34) to [a change](https://github.com/fortanix/pkix/commit/9a08c7fdd4aa85e6cdfa17f7cac5c707d5c81969) in the `DateTime` type. This type isn't used by `em-app`.
Fixed #562
=> Indicate that `em-app` is compatible with both `pkix` 0.1 and 0.2 versions

.github/workflows/build.yml, examples/mem-correctness-test/Cargo.toml, examples/mem-correctness-test/src/main.rs
This is a test that tests the correctness of our new allocator snmalloc. This test should run continuosly and should not crash. 
The pseudocode is taken from https://fortanix.atlassian.net/wiki/spaces/PLAT/pages/3155820642/Memory+Allocators
We should modify the configurable parameters https://github.com/fortanix/rust-sgx/blob/memory-correctness-test/examples/mem-correctness-test/src/main.rs#L43 and also modify the ```heap-size```  parameter in ```rust-sgx/examples/mem-correctness-test/Cargo.toml``` file then simply do the following
``` cd rust-sgx/examples/mem-correctness-test/
cargo run --target x86_64-fortanix-unknown-sgx
```
=> Adding a test that will test the correctness of snmalloc

Cargo.lock, em-app/Cargo.toml, em-app/examples/get-certificate/Cargo.toml, examples/tls/Cargo.toml, fortanix-vme/aws-nitro-enclaves/nitro-attestation-verify/Cargo.toml, intel-sgx/dcap-ql/Cargo.toml, intel-sgx/ias/Cargo.toml, intel-sgx/sgx-isa/Cargo.toml
Update dependence mbedtls version to `0.12.X`.
Update or correct the new version number of crates to be published.
=> Upgrade dependence of mbedtls and prepare for releases

Cargo.lock, Cargo.toml, intel-sgx/async-usercalls/Cargo.toml, intel-sgx/enclave-runner/Cargo.toml, ipc-queue/Cargo.toml
- ipc-queue crates contains breaking changes, so need to bump version before publishing.
=> bump version of ipc-queue for new release

.gitignore, .idea/encodings.xml, Cargo.lock, Cargo.toml, examples/backtrace_panic/Cargo.toml, examples/mem-alloc-test/Cargo.toml, examples/mem-correctness-test/Cargo.toml, examples/mpsc-crypto-mining/Cargo.toml, examples/unit_tests/Cargo.toml, examples/usercall-extension-bind/app/Cargo.toml, examples/usercall-extension-bind/runner/Cargo.toml, examples/usercall-extension/app/Cargo.toml, examples/usercall-extension/runner/Cargo.toml, fortanix-vme/aws-nitro-enclaves/nitro-attestation-verify/Cargo.toml, fortanix-vme/aws-nitro-enclaves/tests/nsm-test/Cargo.toml, fortanix-vme/vme-pkix/Cargo.toml, intel-sgx/ias/Cargo.toml
- Update required pkix version for some crates.
- Bump ias version.
- Bump vme-pkix version.
- Add missing `publish = false`.
- Correct workspace exclude syntax.
=> Update pkix version

.github/dependabot.yml
Stop grouping Dependabot version updates and Dependabot security updates.
=> chore: stop grouping dependabot version update

examples/mem-alloc-test/src/main.rs, examples/mem-correctness-test/src/main.rs
Adding some documentation for the parameters and test description for ```rust-sgx/examples/mem-alloc-test``` and ```rust-sgx/examples/mem-correctness-test```
=> Adding some documentation for the parameters and test description memory allocator tests

intel-sgx/dcap-artifact-retrieval/src/provisioning_client/intel.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/mod.rs, intel-sgx/pcs/src/pckcrl.rs, intel-sgx/pcs/src/pckcrt.rs, intel-sgx/pcs/src/qe_identity.rs, intel-sgx/pcs/src/tcb_info.rs
Adds caching functionality for `dcap-artifact-retrieval-tool` that caches API responses in memory. In detail the cache is implemented for `CachedService` type which is similar to `BackoffService` in a sense that it wraps a caching functionality around a call to the underlying service:
```
self.service.call_service::<F>(fetcher, input)
```
The cache itself is a `LruCache` with a capacity specified by user.
=> Adds cache to dcap-artifact-retrieval-tool

Cargo.lock, Cargo.toml, em-app/Cargo.toml, em-app/src/utils.rs
Updated `em-app` to use latest version of `em-client` which check application config hash before returning it as a result. Corresponding PR is: https://github.com/fortanix/em-client-rust/pull/3.
=> Use updated em-client

intel-sgx/dcap-artifact-retrieval/Cargo.toml, intel-sgx/pcs/Cargo.toml
This is needed before we can publish `pcs` and `dcap-artifact-retrieval` crates.
=> Add missing version for pcs and dcap-artifact-retrieval dependencies

intel-sgx/dcap-artifact-retrieval/Cargo.toml, intel-sgx/pcs/Cargo.toml
This is also needed to publish these crates.
=> Fix missing fields in Cargo.toml of pcs and dcap-artifact-retrieval crates

Cargo.lock, intel-sgx/async-usercalls/Cargo.toml, intel-sgx/async-usercalls/src/callback.rs, intel-sgx/async-usercalls/src/provider_api.rs, intel-sgx/async-usercalls/src/raw.rs, intel-sgx/async-usercalls/src/test_support.rs, intel-sgx/enclave-runner/Cargo.toml, intel-sgx/enclave-runner/src/command.rs, intel-sgx/enclave-runner/src/library.rs, intel-sgx/enclave-runner/src/loader.rs, intel-sgx/enclave-runner/src/usercalls/interface.rs, intel-sgx/enclave-runner/src/usercalls/mod.rs, intel-sgx/fortanix-sgx-abi/Cargo.toml, intel-sgx/fortanix-sgx-abi/src/lib.rs, ipc-queue/Cargo.toml
SGXv2 platforms support calling the rdtscp instruction inside an enclave. This PR piggy backs on #659 that implemented logic to keep track of time. This PR starts using this logic in various tools and crates (e.g., async-usercalls, enclave-runner, ...).
Note that the enclave-runner _does not_ change the returned value of `insecure_time` usercalls at this point; it will always return a null pointer as the second value in the returned tuple. These changes can thus be used on all existing enclaves, no new Rust compiler is required. Another PR will be filed to change the default behavior of enclave runner so enclaves by default take advantage of their improved hardware capabilities.
=> Support letting enclaves do time keeping

Cargo.lock, intel-sgx/dcap-artifact-retrieval/Cargo.toml, intel-sgx/dcap-artifact-retrieval/src/cli.rs
Also fixed CLI arg descriptions that were inaccurate or poorly worded.
=> dcap-artifact-retrieval: Use v4 APIs by default in CLI tool.

.github/workflows/build.yml, Cargo.lock, intel-sgx/dcap-artifact-retrieval/Cargo.toml, intel-sgx/dcap-artifact-retrieval/src/lib.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/intel.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/mod.rs
Original `native-tls` in `dcap-artifact-retrieval` wont work in distroless container where no root CA is
provided by system.
The solution I proposed here is adding support for choosing  `rustls` as TLS provider for `reqwest`, `rustls` will use [webpki-roots](https://crates.io/crates/webpki-roots) for default root CAs.
- Add feature `rustls-tls`
- Add/update functions for creating a reqwest client.
- Add test cases in CI for dcap-artifact-retrieval using rustls.
=>  [DEVOPS-5452] Support different tls for dcap-artifact-retrieval

intel-sgx/aesm-client/src/lib.rs, intel-sgx/enclave-runner/src/command.rs, intel-sgx/enclave-runner/src/loader.rs, intel-sgx/enclave-runner/src/usercalls/mod.rs, ipc-queue/src/fifo.rs, ipc-queue/src/lib.rs, ipc-queue/src/position.rs
This change allows users of this library to specify the number of worker threads. This lets users limit the number of cores used by an enclave. 
This is a backwards-compatible change.
=> Allow specifying number of worker threads used to run an enclave

intel-sgx/pcs/src/qe_identity.rs, intel-sgx/pcs/src/tcb_info.rs
Expose the `tcb_evaluation_data_number` fields in the `TcbData` and `QeIdentity`.
I've changed the type of `tcb_evaluation_data_number` in `QeIdentity` from `u32` to `u64` to be in line with `TcbData`
=> Expose `tcb_evaluation_data_number` fields

intel-sgx/dcap-artifact-retrieval/src/provisioning_client/intel.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/pccs.rs
By default we want to fetch the "early" variant of DCAP artifacts. See the [pcs](https://api.portal.trustedservices.intel.com/content/documentation.html#pcs-tcb-info-model-v3) API documentation.
=> [RTE-241] Always fetch early variant of DCAP artifacts

Cargo.lock, intel-sgx/enclave-runner/Cargo.toml
According to `cargo semver-check` this is a semver-compatible change.
Disclosure: the following dependencies of `enclave-runner` have been updated (since v0.6.0 release of `enclave-runner`):
- `fortanix-sgx-abi`: `0.5.0` -> `0.6.0`
- `ipc_queue`: `0.2.0` -> `0.3.0`
=> Bump `enclave_runner` version to `0.6.1`

intel-sgx/dcap-artifact-retrieval/src/provisioning_client/mod.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/pccs.rs, intel-sgx/pcs/src/pckcrt.rs, intel-sgx/pcs/src/tcb_info.rs
This should address PROD-9810.
=> Fix `pckcerts_with_fallback` logic to retrieve TCB info and get PCK certs for each TCB level

Cargo.lock, intel-sgx/aesm-client/Cargo.toml, intel-sgx/dcap-provider/Cargo.toml, intel-sgx/dcap-ql/Cargo.toml, intel-sgx/dcap-retrieve-pckid/Cargo.toml, intel-sgx/enclave-runner/Cargo.toml, intel-sgx/fortanix-sgx-tools/Cargo.toml, intel-sgx/ias/Cargo.toml, intel-sgx/report-test/Cargo.toml, intel-sgx/sgxs-loaders/Cargo.toml, intel-sgx/sgxs-tools/Cargo.toml
Also:
- sgxs-tools: 0.8.6 -> 0.9.0
- report-test: 0.4.0 -> 0.5.0
- dcap-provider: 0.4.0 -> 0.5.0
- dcap-retrieve-pckid: 0.2.0 -> 0.3.0
These are all published crates that (transitively) depend on `enclave-runner`, so we should bump their versions as well, and publish new versions of them if/when needed.
See this comment: https://github.com/fortanix/rust-sgx/pull/681#issuecomment-2616354292 for why we decided to bump enclave runner to a semver-incompatible version.
=> Bump `enclave-runner` to `v0.7.0` (also bump dependent crates `sgx-tools`, `report-test`, `dcap-provider`, and `dcap-retrieve-pkcid`)

.github/workflows/build.yml, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/pccs.rs
- Load url from env for pccs provider tests.
- Run these tests only when url is provided by env var `PCCS_URL`.
=> Update dcap-artifact-retrieval PCCS provider tests

Cargo.lock, intel-sgx/dcap-artifact-retrieval/Cargo.toml, intel-sgx/insecure-time/Cargo.toml, intel-sgx/pcs/Cargo.toml
To publish new version of crates in https://github.com/fortanix/rust-sgx/pull/690
There are still some work to do:
- Publish `insecure-time`
Also this PR bump version of `dcap-artifact-retrieval` to publish new version that include bug fix.
=> Update Cargo.toml files for publish new versions

intel-sgx/fortanix-sgx-abi/src/lib.rs
The error is related to captured metavariables in macros:
```
error: no rules expected `ty` metavariable
--> intel-sgx/async-usercalls/src/callback.rs:67:1
|
23 | macro_rules! cbfn_type {
| ---------------------- when calling this macro
...
67 | invoke_with_usercalls!(define_callback);
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no rules expected this token in macro call
|
note: while trying to match `!`
--> intel-sgx/async-usercalls/src/callback.rs:25:10
|
25 |     ( -> ! )                              => { () };
|          ^
= note: captured metavariables except for `:tt`, `:ident` and `:lifetime` cannot be compared to other tokens
= note: see <https://doc.rust-lang.org/nightly/reference/macros-by-example.html#forwarding-a-matched-fragment> for more information
= help: try using `:tt` …
```
=> Fix compile error introduced by the new toolchain

Cargo.lock, fortanix-vme/aws-nitro-enclaves/eif-tools/Cargo.toml
On ubuntu24 we are seeing segmentation fault caused by sha2 crate (0.9.5 version)
```
0x00005555558cc6d0 in sha2::sha512::x86::sha512_compress_x86_64_avx2 ()
(gdb) bt
#0  0x00005555558cc6d0 in sha2::sha512::x86::sha512_compress_x86_64_avx2 ()
#1  0x00005555558cc51e in sha2::sha512::Engine512::finish ()
#2  0x00005555558cc5df in <sha2::sha512::Sha384 as digest::fixed::FixedOutputDirty>::finalize_into_dirty ()
#3  0x000055555580dd93 in eif_defs::eif_hasher::EifHasher<T>::new ()
#4  0x000055555573dbd9 in eif_utils::EifBuilder<T>::new ()
#5  0x00005555557432e6 in enclave_build::Docker2Eif::create ()
#6  0x000055555572636e in nitro_cli::build_from_docker ()
#7  0x0000555555718fb6 in ftxvme_elf2eif::main ()
#8  0x0000555555715c13 in std::sys::backtrace::__rust_begin_short_backtrace ()
#9 …
```
=> Update sha2 version to 0.10.8

Cargo.lock, intel-sgx/async-usercalls/Cargo.toml
Because its dependencies have been bumped:
- ipc-queue: 0.3 -> 0.4
- fortanix-sgx-abi: 0.5 -> 0.6
=> Bump `async-usercalls` version to `0.6.0`

.github/workflows/build.yml, doc/generate-api-docs.sh, intel-sgx/fortanix-sgx-abi/src/lib.rs
Compiling `async-usercalls` triggers an upstream compiler bug in `nightly-2025-02-23` or subsequent compilers. This PR pins some CI tests to the `nightly-2025-02-22` compiler until the bug is resolved upstream. A minimal PoC still needs to be created and a bug report still needs to be filed.
=> [RTE-381] Pin to `nightly-2025-02-22` compiler for some CI tests

Cargo.lock, intel-sgx/dcap-artifact-retrieval/Cargo.toml
I recently updated the pcs version in [PR](https://github.com/fortanix/rust-sgx/pull/722). Updating patch version here to publish and sort version mismatch issue.
=> Update dcap-artifact-retrieval patch version

Cargo.lock, intel-sgx/dcap-artifact-retrieval/Cargo.toml, intel-sgx/pcs/Cargo.toml, intel-sgx/pcs/src/qe_identity.rs, intel-sgx/pcs/src/tcb_info.rs
The [Intel PCS](https://api.portal.trustedservices.intel.com/content/documentation.html#pcs) services offers various DCAP artifacts. The TcbInfo comes with an ID that can be used to differentiate TCB info for the SGX and TDX platforms. This ID should be checked during verification. This didn't happen. For the SGX platform, that's not a security issue as for all available FMSPCs the TCB info of TDX is a superset of SGX. It is the other way around.
For QE Identities something similar needs to happen.
=> [RTE-422] Verify identities

Cargo.lock, intel-sgx/dcap-artifact-retrieval/Cargo.toml, intel-sgx/pcs/Cargo.toml
#731 (just merged) bumped the versions of `pcs` and `dcap-artifact-retrieval`. Unfortunately, in parallel these values were already bumped to the same value, and published. This PR rectifies the situation by bumping the versions again for these crates to account for changes made in #731
=> [RTE-422] Bump pcs and dcap-artifact-retrieval

intel-sgx/dcap-artifact-retrieval/src/provisioning_client/azure.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/common.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/intel.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/mod.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/pccs.rs
Intel recently added the new `TcbEvaluationDataNumbers` API endpoint to their [PCS service](https://api.portal.trustedservices.intel.com/content/documentation.html#pcs-retrieve-tcbevalnumbers-v4). This PR adds support to call this endpoint. Parsing the result is left for a future PR for clarity. Also retrieving TcbInfo for a specific evaluation data number is left for a future PR.
=> [RTE-305] Add support for `TcbEvaluationDataNumbers` API endpoint in dcap-artifact-retrieval

.github/workflows/build.yml
CI fails with:
```
running: cd "/home/runner/work/rust-sgx/rust-sgx/target/debug/build/mbedtls-sys-auto-c66539428ec212d0/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mbedtls-sys-auto-2.28.10/vendor" "-DENABLE_PROGRAMS=OFF" "-DENABLE_TESTING=OFF" "-DGEN_FILES=ON" "-DPython3_FIND_FRAMEWORK=LAST" "-DLIB_INSTALL_DIR=lib" "-DCMAKE_INSTALL_PREFIX=/home/runner/work/rust-sgx/rust-sgx/target/debug/build/mbedtls-sys-auto-c66539428ec212d0/out" "-DCMAKE_C_FLAGS= -DMBEDTLS_CONFIG_FILE=\"\\\"/home/runner/work/rust-sgx/rust-sgx/target/debug/build/mbedtls-sys-auto-c66539428ec212d0/out/config.h\\\"\" -ffunction-sections -fdata-sections -fPIC -m64 --target=x86_64-unknown-linux-gnu" "-DCMAKE_C_COMPILER=/usr/bin/clang-18" "-DCMAKE_CXX_FLAGS= …
```
=> [RTE-427] Ensure minimual Cmake policy of 3.5

intel-sgx/dcap-artifact-retrieval/src/cli.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/intel.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/mod.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/pccs.rs, intel-sgx/pcs/src/tcb_evaluation_data_numbers.rs, intel-sgx/pcs/src/tcb_info.rs
Intel recently added the new TcbEvaluationDataNumbers API endpoint to their [PCS service](https://api.portal.trustedservices.intel.com/content/documentation.html#pcs-retrieve-tcbevalnumbers-v4). This PR:
- adds support to fetch TCB info based on the fmspc and TCB Evaluation Data Number
- ensures the dcap artifact retrieval tool downloads all required information one may need for offline attestation
-
=> [RTE-423] Get tcb info by evaluation data number

intel-sgx/dcap-artifact-retrieval/src/cli.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/azure.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/intel.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/mod.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/pccs.rs
This PR:
- Adds support to dcap artifact retrieval tool to fetch QE identity data based on TCB Evaluation Data Number
- Changes the API to fetch TCB info to keep it in line with how it stores/retrieves stored artifacts
=> [RTE-428] Fetching QeIdentity with TCB Evaluation Data Number

intel-sgx/pcs/src/tcb_evaluation_data_numbers.rs
This brings the `RawTcbEvaluationDataNumbers` struct in line with other DCAP artifact structs.
=> Add `write_to_file_if_not_exist()` method to `RawTcbEvaluationDataNumbers` struct

Cargo.lock, intel-sgx/pcs/Cargo.toml
#745 updates the `pcs` crate, but forgot to bump the version. This PR fixes that.
=> Bump pcs to version 0.6.1

.github/workflows/build.yml, doc/generate-api-docs.sh, intel-sgx/fortanix-sgx-abi/src/lib.rs
https://github.com/rust-lang/rust/issues/138975#issuecomment-2755866121 concluded that the breakage described and fixed in https://github.com/fortanix/rust-sgx/pull/708 was an issue with our macros being used cross-crate and using nested macros, and that the fix proposed in https://github.com/fortanix/rust-sgx/pull/708 is indeed the right one
This PR cherry-picks https://github.com/fortanix/rust-sgx/pull/708 and reverts the compiler pinning we required in https://github.com/fortanix/rust-sgx/pull/713.
The PR has already been tested to compile locally with the following compilers:
* `nightly-2025-02-22` (compiler version used in https://github.com/fortanix/rust-sgx/issues/725, which turned out to be a `deranged` crate issue)
* `nightly-2025-04-17` (testing with a recent nightly)
* …
=> [RTE-445] Ensure Rust SGX CI works against latest rust nightly

intel-sgx/aesm-client/src/lib.rs
Allow `mismatched_lifetime_syntaxes` lint warning to fix erros in nightly
```
error: lifetime flowing from input to output with different syntax can be confusing
--> /home/yuxiangcao/github_ws/fortanix/rust-sgx/target/x86_64-fortanix-unknown-sgx/debug/build/aesm-client-7553ee8116cfb248/out/aesm_proto.rs:952:15
|
952 |     fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
|               ^^^^^     ------------------------------------ the lifetime gets resolved as `'_`
|               |
|               this lifetime flows to the output
|
note: the lint level is defined here
--> intel-sgx/aesm-client/src/lib.rs:19:9
|
19  | #![deny(warnings)]
|         ^^^^^^^^
= note: `#[deny(mismatched_lifetime_syntaxes)]` implied by `#[deny(warnings)]`
help: one option is to remove the lifetime …
```
=> Ignore mismatched_lifetime_syntaxes lint warning in nightly

.github/workflows/build.yml, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/intel.rs, intel-sgx/dcap-artifact-retrieval/src/provisioning_client/pccs.rs
1. Intel SGX PCS version 3 is scheduled to end of life not later than October 31, 2025.  So we no longer force to test it.
2. PCCS tests default to use production PCCS url.
3. Update GitHub action to avoid empty string for PCS_API_KEY and PCCS_URL when CI is running from fork.
=> Fix CI for 3rd party

intel-sgx/scripts/gdb.py
Python 3.12 recently changed how it parses string escapes, so it now warns on unrecognized escape codes. Trying to `source intel-sgx/scripts/gdb.py` in a recent `gdb` install results in these error messages:
```bash
$ nix shell github:NixOS/nixpkgs/release-24.11#gdb
$ gdb
GNU gdb (GDB) 15.2
(gdb) python-interactive
>>> import sys
>>> sys.version
'3.12.8 (main, Dec  3 2024, 18:42:41) [GCC 13.3.0]'
>>> ^D
(gdb) source intel-sgx/scripts/gdb.py
intel-sgx/scripts/gdb.py:72: SyntaxWarning: invalid escape sequence '\s'
m = re.match("^(?:\s*0x[0-9a-fA-F]+\s){4}", l)
intel-sgx/scripts/gdb.py:100: SyntaxWarning: invalid escape sequence '\s'
m=re.match('^\s+\[\s*(\d+)\]\s+(\.text)\s+(\S+)\s+([0-9a-fA-F]+)\s', line)
(gdb)
```
With an older gdb+python:
```bash
$ nix shell …
```
=> sgx: gdb: fix syntax warning in python 3.12+

intel-sgx/enclave-runner/src/usercalls/mod.rs
We forward enclave panics (i.e., panic if the enclave panics) inside a tokio task, which results in tokio eating up the panic. This is the exact opposite of the intended behavior of `forward_panics`. This PR makes the runner panic outside tokio tasks, so the panic won't be caught by tokio.
Closes #763
=> Do not let tokio swallow forwarded panics

Cargo.lock, intel-sgx/enclave-runner/Cargo.toml, intel-sgx/fortanix-sgx-abi/Cargo.toml
Changes since 0.6.0:
- Fix compile error introduced by new rustc
=> Bump `fortanix-sgx-abi` to 0.6.1

Cargo.lock, em-app/Cargo.toml
Bump em-app version from 0.5.0 to 0.5.1.
This is needed to have an `em-app` that support mbedtls 0.13.X
Change log of new release:
- Updates b64-ct from 0.1.0 to 0.1.3
- Updates mbedtls from 0.12 to `>=0.12.0, <0.14.0`
- Updates serde from 1.0.123 to 1.0
- Updates serde_derive from 1.0.123 to 1.0
=> [PROD-8063] Release new version of em-app 0.5.1

intel-sgx/dcap-artifact-retrieval/src/cli.rs
This small PR mainly change  dcap-artifact-retrieval tool to print full encrypted PPID in verbose logging.
This is very helpful during debugging, test and CI.
=> DEVOPS-5899 Improve verbose logging for dcap-artifact-retrieval tool

Cargo.lock, intel-sgx/dcap-artifact-retrieval/Cargo.toml, intel-sgx/fortanix-sgx-tools/Cargo.toml, intel-sgx/sgxs-tools/Cargo.toml
- This PR bumps version of following crates to prepare binary release:
- dcap-artifact-retrieval
- fortanix-sgx-tools
- sgxs-tools
- This PR also fixes the readme path issue in Cargo.toml
After bump version, we can use this newly added GitHub Action to create release with binary + crates.io new version: https://github.com/fortanix/rust-sgx/actions/workflows/release.yml
=> Bump version for tools that need release binaries

intel-sgx/enclave-runner/src/loader.rs, intel-sgx/sgxs-loaders/src/isgx/mod.rs
There are two issues with running SGX enclaves on Sapphire Rapids:
- When running debug enclaves, we used to use XCR0 unmodified for the xfrm attribute. But now advanced matrix extensions (AMX) may lead to larger SSA frames (3 pages) than expected. The elf2sgxs tool by default only selected 1 page for SSA frames. When generating a signature, we need to ensure features are turned off when they would lead to larger SSA frames.
- Turning features off, may conflict with one another. XTILECFG and XTILEDATA need to be either enabled both, or disabled both. This PR sets the xfrm attribute accordingly.
Address #565
=> [RTE-370] Generate valid xfrm when required

Cargo.lock, intel-sgx/dcap-retrieve-pckid/Cargo.toml, intel-sgx/enclave-runner/Cargo.toml, intel-sgx/report-test/Cargo.toml
- Bump enclave-runner version to have new version to include https://github.com/fortanix/rust-sgx/pull/694/
- Bump report-test version & its dependent version  on enclave-runner
- Bump dcap-retrieve-pckid version & its dependent  version on report-test
=> Bump crates version for xfrm fix 
